import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    topSection: {
        backgroundColor: '#16a34a',
        borderBottomLeftRadius: 32,
        borderBottomRightRadius: 32,
        paddingBottom: 10,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 15,
    },
    backBtn: {
        padding: 5,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '900',
        color: '#fff',
    },
    saveHeaderBtn: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 16,
    },
    content: {
        flex: 1,
    },
    scrollContent: {
        padding: 20,
        paddingBottom: 120,
    },
    catalogBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 20,
        marginBottom: 25,
        shadowColor: '#16a34a',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 3,
    },
    catalogIcon: {
        width: 45,
        height: 45,
        borderRadius: 12,
        backgroundColor: '#f0fdf4',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    catalogTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0f172a',
    },
    catalogSubtitle: {
        fontSize: 12,
        color: '#64748b',
        marginTop: 2,
    },
    sectionHeader: {
        marginBottom: 10,
        paddingHorizontal: 5,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: '800',
        color: '#0f172a',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    sectionSubtitle: {
        fontSize: 12,
        color: '#94a3b8',
        marginTop: 2,
    },
    itemCard: {
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    itemMainInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    itemThumb: {
        width: 50,
        height: 50,
        borderRadius: 10,
        backgroundColor: '#f8fafc',
    },
    itemName: {
        fontSize: 15,
        fontWeight: '700',
        color: '#1e293b',
    },
    itemBrand: {
        fontSize: 12,
        color: '#94a3b8',
    },
    removeBtn: {
        padding: 5,
    },
    itemFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 15,
        paddingTop: 15,
        borderTopWidth: 1,
        borderTopColor: '#f1f5f9',
    },
    quantityLabel: {
        fontSize: 13,
        fontWeight: '600',
        color: '#64748b',
    },
    counter: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f1f5f9',
        borderRadius: 10,
        padding: 4,
    },
    counterBtn: {
        width: 30,
        height: 30,
        borderRadius: 8,
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    counterValue: {
        fontSize: 15,
        fontWeight: '800',
        color: '#1e293b',
        marginHorizontal: 15,
    },
    footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: 20,
        paddingBottom: Platform.OS === 'ios' ? 40 : 20,
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#f1f5f9',
    },
    saveBtn: {
        backgroundColor: '#16a34a',
        height: 55,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#16a34a',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    saveBtnText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '800',
    },
    disabledBtn: {
        opacity: 0.5,
        backgroundColor: '#94a3b8',
    },
    emptyContainer: {
        alignItems: 'center',
        paddingVertical: 40,
    },
    emptyText: {
        marginTop: 10,
        fontSize: 14,
        color: '#94a3b8',
        fontWeight: '500',
    },
    itemBrandRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 2,
    },
    itemCatalogCat: {
        fontSize: 11,
        color: '#64748b',
        fontWeight: '600',
    },
    dot: {
        width: 3,
        height: 3,
        borderRadius: 2,
        backgroundColor: '#cbd5e1',
        marginHorizontal: 6,
    },
});
