import { Dimensions, StyleSheet } from 'react-native';

const { height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    scrollContainer: {
        paddingBottom: 150,
    },
    headerBackground: {
        height: height * 0.28,
        backgroundColor: '#16a34a',
        paddingHorizontal: 25,
        justifyContent: 'center',
    },
    headerCurve: {
        position: 'absolute',
        bottom: -25,
        left: 0,
        right: 0,
        height: 50,
        backgroundColor: '#f8fafc',
        borderTopLeftRadius: 40,
        borderTopRightRadius: 40,
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 10,
    },
    headerInfo: {
        flex: 1,
    },
    welcomeText: {
        fontSize: 16,
        color: 'rgba(255,255,255,0.8)',
    },
    headerTitle: {
        fontSize: 30,
        fontWeight: 'bold',
        color: '#fff',
        marginTop: 10,
    },
    logoutBtn: {
        width: 45,
        height: 45,
        borderRadius: 15,
        backgroundColor: 'rgba(255,255,255,0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    bgIcon1: {
        position: 'absolute',
        top: 20,
        right: 20,
    },
    bgIcon2: {
        position: 'absolute',
        bottom: 40,
        left: -10,
    },
    contentBody: {
        flex: 1,
        backgroundColor: '#f8fafc',
        marginTop: -10,
    },
    statsRow: {
        flexDirection: 'row',
        marginHorizontal: 20,
        backgroundColor: '#fff',
        borderRadius: 25,
        padding: 20,
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        justifyContent: 'space-between',
        marginTop: -35,
    },
    statBox: {
        alignItems: 'center',
        flex: 1,
    },
    statCircle: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    statValue: {
        fontSize: 18,
        fontWeight: '900',
        color: '#0f172a',
    },
    statLabel: {
        fontSize: 11,
        color: '#94a3b8',
        fontWeight: '600',
    },
    section: {
        marginTop: 30,
        paddingHorizontal: 25,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    sectionTitle: {
        fontSize: 20,
        color: '#1e293b',
        fontWeight: '500',
    },
    boldText: {
        fontWeight: '900',
        color: '#0f172a',
    },
    searchInputContainer: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        borderRadius: 18,
        paddingLeft: 20,
        alignItems: 'center',
        height: 60,
        borderWidth: 1,
        borderColor: '#f1f5f9',
        marginTop: 15,
    },
    input: {
        flex: 1,
        fontSize: 15,
        color: '#1e293b',
    },
    addInlineBtn: {
        backgroundColor: '#16a34a',
        width: 48,
        height: 48,
        borderRadius: 14,
        marginRight: 6,
        justifyContent: 'center',
        alignItems: 'center',
    },
    chipsPadding: {
        paddingLeft: 25,
        paddingVertical: 10,
    },
    chip: {
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 15,
        backgroundColor: '#fff',
        marginRight: 10,
        borderWidth: 1,
        borderColor: '#f1f5f9',
    },
    activeChip: {
        backgroundColor: '#16a34a',
        borderColor: '#16a34a',
    },
    chipText: {
        color: '#64748b',
        fontWeight: '700',
        fontSize: 13,
    },
    activeChipText: {
        color: '#fff',
    },
    listCard: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 22,
        alignItems: 'center',
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#f1f5f9',
    },
    cardImagePlaceholder: {
        width: 55,
        height: 55,
        borderRadius: 16,
        backgroundColor: '#edfdf3',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    cardContent: {
        flex: 1,
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: '900',
        color: '#0f172a',
    },
    cardSubtitle: {
        fontSize: 12,
        color: '#94a3b8',
        marginTop: 2,
        fontWeight: '500',
    },
    emptyState: {
        alignItems: 'center',
        paddingVertical: 40,
    },
    emptyIconContainer: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#f1f5f9',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    emptyTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#475569',
        marginBottom: 8,
    },
    emptySubtitle: {
        fontSize: 14,
        color: '#94a3b8',
        textAlign: 'center',
        lineHeight: 20,
    },
    fabContainer: {
        position: 'absolute',
        bottom: 30,
        left: 0,
        right: 0,
        alignItems: 'center',
    },
    fab: {
        width: 70,
        height: 70,
        borderRadius: 35,
        backgroundColor: '#16a34a',
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 8,
        shadowColor: '#16a34a',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.4,
        shadowRadius: 12,
    }
});
